//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuskomDiagnostics.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".. Запрос баланса .. ")]
        public string BalanceString {
            get {
                return ((string)(this["BalanceString"]));
            }
            set {
                this["BalanceString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ShowBalloonTipWithShortMilliseconds {
            get {
                return ((int)(this["ShowBalloonTipWithShortMilliseconds"]));
            }
            set {
                this["ShowBalloonTipWithShortMilliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int ShowBalloonTipWithGreatMilliseconds {
            get {
                return ((int)(this["ShowBalloonTipWithGreatMilliseconds"]));
            }
            set {
                this["ShowBalloonTipWithGreatMilliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(0%")]
        public string ConnectionsFineQualitySymptom {
            get {
                return ((string)(this["ConnectionsFineQualitySymptom"]));
            }
            set {
                this["ConnectionsFineQualitySymptom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<нет значения>")]
        public string EmptyColumnValue {
            get {
                return ((string)(this["EmptyColumnValue"]));
            }
            set {
                this["EmptyColumnValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Колонка")]
        public string DefaultColumnName {
            get {
                return ((string)(this["DefaultColumnName"]));
            }
            set {
                this["DefaultColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RuskomDiagnostic")]
        public string ApplicationIdentificator {
            get {
                return ((string)(this["ApplicationIdentificator"]));
            }
            set {
                this["ApplicationIdentificator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int Windows7MajorVersion {
            get {
                return ((int)(this["Windows7MajorVersion"]));
            }
            set {
                this["Windows7MajorVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Windows7MinorVersion {
            get {
                return ((int)(this["Windows7MinorVersion"]));
            }
            set {
                this["Windows7MinorVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Одновременно может работать только одна программа диагностики")]
        public string AllowOnlyOneProgramInstance {
            get {
                return ((string)(this["AllowOnlyOneProgramInstance"]));
            }
            set {
                this["AllowOnlyOneProgramInstance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Отсутствует подключение к сети или неверные настройки сети")]
        public string DisconnectOrInvalidConnection {
            get {
                return ((string)(this["DisconnectOrInvalidConnection"]));
            }
            set {
                this["DisconnectOrInvalidConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Баланс лицевого счёта не известен")]
        public string RequestBalanceFail {
            get {
                return ((string)(this["RequestBalanceFail"]));
            }
            set {
                this["RequestBalanceFail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FAIL")]
        public string BalanceTypeRequestFail {
            get {
                return ((string)(this["BalanceTypeRequestFail"]));
            }
            set {
                this["BalanceTypeRequestFail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ok")]
        public string BalanceTypeRequestOk {
            get {
                return ((string)(this["BalanceTypeRequestOk"]));
            }
            set {
                this["BalanceTypeRequestOk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int PingTimeout {
            get {
                return ((int)(this["PingTimeout"]));
            }
            set {
                this["PingTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int SmallPingPackageSize {
            get {
                return ((int)(this["SmallPingPackageSize"]));
            }
            set {
                this["SmallPingPackageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public int BigPingPackageSize {
            get {
                return ((int)(this["BigPingPackageSize"]));
            }
            set {
                this["BigPingPackageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MeasuresCount {
            get {
                return ((int)(this["MeasuresCount"]));
            }
            set {
                this["MeasuresCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RuskomDiagnosticsRunPath")]
        public string RuskomDiagnosticsRunPath {
            get {
                return ((string)(this["RuskomDiagnosticsRunPath"]));
            }
            set {
                this["RuskomDiagnosticsRunPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://89.106.251.215/")]
        public string UpdateStorageLocation {
            get {
                return ((string)(this["UpdateStorageLocation"]));
            }
            set {
                this["UpdateStorageLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("version.info")]
        public string UpdateVersionFilename {
            get {
                return ((string)(this["UpdateVersionFilename"]));
            }
            set {
                this["UpdateVersionFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Вышла новая версия, обновить ?")]
        public string NewVersionAvailable {
            get {
                return ((string)(this["NewVersionAvailable"]));
            }
            set {
                this["NewVersionAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("anonymous")]
        public string AnonimusFtpUserName {
            get {
                return ((string)(this["AnonimusFtpUserName"]));
            }
            set {
                this["AnonimusFtpUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rk1@rk1.ru")]
        public string AnonimusPassword {
            get {
                return ((string)(this["AnonimusPassword"]));
            }
            set {
                this["AnonimusPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ошибка загрузки обновления")]
        public string DownloadFail {
            get {
                return ((string)(this["DownloadFail"]));
            }
            set {
                this["DownloadFail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Обновление установлено, перезапустить приложение ?")]
        public string QuestionPerformRestart {
            get {
                return ((string)(this["QuestionPerformRestart"]));
            }
            set {
                this["QuestionPerformRestart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Установлена актуальная версия, обновления не требуется")]
        public string ActualVersionInstalled {
            get {
                return ((string)(this["ActualVersionInstalled"]));
            }
            set {
                this["ActualVersionInstalled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string ResultComponentsDelimiter {
            get {
                return ((string)(this["ResultComponentsDelimiter"]));
            }
            set {
                this["ResultComponentsDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iperf.exe")]
        public string SpeedTestExecutable {
            get {
                return ((string)(this["SpeedTestExecutable"]));
            }
            set {
                this["SpeedTestExecutable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cyggcc_s-1.dll")]
        public string SpeedTestLibrary1 {
            get {
                return ((string)(this["SpeedTestLibrary1"]));
            }
            set {
                this["SpeedTestLibrary1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cygstdc++-6.dll")]
        public string SpeedTestLibrary2 {
            get {
                return ((string)(this["SpeedTestLibrary2"]));
            }
            set {
                this["SpeedTestLibrary2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cygwin1.dll")]
        public string SpeedTestLibrary3 {
            get {
                return ((string)(this["SpeedTestLibrary3"]));
            }
            set {
                this["SpeedTestLibrary3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-y C -c")]
        public string SpeedTestProgramArguments {
            get {
                return ((string)(this["SpeedTestProgramArguments"]));
            }
            set {
                this["SpeedTestProgramArguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ping.exe")]
        public string PingExecutable {
            get {
                return ((string)(this["PingExecutable"]));
            }
            set {
                this["PingExecutable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tracert.exe")]
        public string TracertExecutable {
            get {
                return ((string)(this["TracertExecutable"]));
            }
            set {
                this["TracertExecutable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-w 1000")]
        public string TracertArguments {
            get {
                return ((string)(this["TracertArguments"]));
            }
            set {
                this["TracertArguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TimeComponentIndex {
            get {
                return ((int)(this["TimeComponentIndex"]));
            }
            set {
                this["TimeComponentIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SpeedTestIpComponentIndex {
            get {
                return ((int)(this["SpeedTestIpComponentIndex"]));
            }
            set {
                this["SpeedTestIpComponentIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int TestingPeriodComponentIndex {
            get {
                return ((int)(this["TestingPeriodComponentIndex"]));
            }
            set {
                this["TestingPeriodComponentIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int DataSentVolumeComponentIndex {
            get {
                return ((int)(this["DataSentVolumeComponentIndex"]));
            }
            set {
                this["DataSentVolumeComponentIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int NetworkSpeedComponentIndex {
            get {
                return ((int)(this["NetworkSpeedComponentIndex"]));
            }
            set {
                this["NetworkSpeedComponentIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\n")]
        public string NewLinesSymptom {
            get {
                return ((string)(this["NewLinesSymptom"]));
            }
            set {
                this["NewLinesSymptom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Настроена автозапуска другой версии, автоматически запускать эту версию?")]
        public string LetAutorunThisVersionQuestion {
            get {
                return ((string)(this["LetAutorunThisVersionQuestion"]));
            }
            set {
                this["LetAutorunThisVersionQuestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Запускать приложение автоматически при загрузке ? ")]
        public string LetAutorunApplicationQuestion {
            get {
                return ((string)(this["LetAutorunApplicationQuestion"]));
            }
            set {
                this["LetAutorunApplicationQuestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ошибка добавления в Автозагрузку")]
        public string AutorunEnablingError {
            get {
                return ((string)(this["AutorunEnablingError"]));
            }
            set {
                this["AutorunEnablingError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ошибка удаления из Автозагрузки")]
        public string AutorunDisablingError {
            get {
                return ((string)(this["AutorunDisablingError"]));
            }
            set {
                this["AutorunDisablingError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Файл \'{0}\' существует, при его удалении произошла ошибка")]
        public string DeletingFileError {
            get {
                return ((string)(this["DeletingFileError"]));
            }
            set {
                this["DeletingFileError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("999")]
        public int PostRequestTimeout {
            get {
                return ((int)(this["PostRequestTimeout"]));
            }
            set {
                this["PostRequestTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Статус измерения {0}, Время {1}, Адрес {2}, Передано {3} (МБайт), Скорость {4} (М" +
            "бит/с) = {5} (МБайт/с);")]
        public string SpeedTestResultAsColumnFormat {
            get {
                return ((string)(this["SpeedTestResultAsColumnFormat"]));
            }
            set {
                this["SpeedTestResultAsColumnFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Проверка скорости локальной сети;{0}Статус измерения {1};{0}Время {2};{0}Скорость" +
            " {5} (Мбит/с) = {6} (МБайт/с);")]
        public string SpeedTestResultAsStringFormat {
            get {
                return ((string)(this["SpeedTestResultAsStringFormat"]));
            }
            set {
                this["SpeedTestResultAsStringFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyyMMddHHmmss")]
        public string SpeedTestParseTimeFormat {
            get {
                return ((string)(this["SpeedTestParseTimeFormat"]));
            }
            set {
                this["SpeedTestParseTimeFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dd.MM.yyyy HH:mm:ss")]
        public string SpeedTestTimeFormat {
            get {
                return ((string)(this["SpeedTestTimeFormat"]));
            }
            set {
                this["SpeedTestTimeFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F")]
        public string TestResultNumericFormat {
            get {
                return ((string)(this["TestResultNumericFormat"]));
            }
            set {
                this["TestResultNumericFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ошибка")]
        public string ActionStatusError {
            get {
                return ((string)(this["ActionStatusError"]));
            }
            set {
                this["ActionStatusError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Сбой")]
        public string ActionStatusFail {
            get {
                return ((string)(this["ActionStatusFail"]));
            }
            set {
                this["ActionStatusFail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Завершено")]
        public string ActionStatusOk {
            get {
                return ((string)(this["ActionStatusOk"]));
            }
            set {
                this["ActionStatusOk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Неопределённый")]
        public string ActionStatusUnknown {
            get {
                return ((string)(this["ActionStatusUnknown"]));
            }
            set {
                this["ActionStatusUnknown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01) Имя <{0}>{1}02) Статус <{2}>{1}03) Карта <{3}>{1}04) Мак адрес <{4}>{1}05) Ай" +
            "пи адрес <{5}>{1}06) Маска <{6}>{1}07) Шлюз <{7}>{1}08) ДэЭнЭс <{8}>{1}")]
        public string ShowRequisitesFormat {
            get {
                return ((string)(this["ShowRequisitesFormat"]));
            }
            set {
                this["ShowRequisitesFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Общая ошибка")]
        public string SendDiagnosticsFail {
            get {
                return ((string)(this["SendDiagnosticsFail"]));
            }
            set {
                this["SendDiagnosticsFail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Status=<{0}> , Message=<{1}>")]
        public string PostDiagnosticsResponceFormat {
            get {
                return ((string)(this["PostDiagnosticsResponceFormat"]));
            }
            set {
                this["PostDiagnosticsResponceFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Качество связи отличное")]
        public string ConnectionFineQuality {
            get {
                return ((string)(this["ConnectionFineQuality"]));
            }
            set {
                this["ConnectionFineQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Обнаружины возможные проблемы с соединением, вы можете связаться со службой техни" +
            "ческой подержки по телефону 221-32-50 с 08 до 23 часов любого дня.")]
        public string ConnectionLoses {
            get {
                return ((string)(this["ConnectionLoses"]));
            }
            set {
                this["ConnectionLoses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Происходит проверка связи. Пожалуйста, ждите.")]
        public string WaitWhileTestProcessed {
            get {
                return ((string)(this["WaitWhileTestProcessed"]));
            }
            set {
                this["WaitWhileTestProcessed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Приложение проверки связи начинает работу")]
        public string DiagnosticsApplicationRunning {
            get {
                return ((string)(this["DiagnosticsApplicationRunning"]));
            }
            set {
                this["DiagnosticsApplicationRunning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Убрать Диагностику из Автозапуска ?")]
        public string DisableDiagnosticsAutorun {
            get {
                return ((string)(this["DisableDiagnosticsAutorun"]));
            }
            set {
                this["DisableDiagnosticsAutorun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Происходит измерение скорости. Не закрывайте это окно.")]
        public string TestingNetworkSpeed {
            get {
                return ((string)(this["TestingNetworkSpeed"]));
            }
            set {
                this["TestingNetworkSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("89.106.248.22")]
        public string SpeedTestServerAddress {
            get {
                return ((string)(this["SpeedTestServerAddress"]));
            }
            set {
                this["SpeedTestServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RuskomDiagnostics")]
        public string ApplicationFilename {
            get {
                return ((string)(this["ApplicationFilename"]));
            }
            set {
                this["ApplicationFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900000")]
        public int CommunicationPeriodMilliseconds {
            get {
                return ((int)(this["CommunicationPeriodMilliseconds"]));
            }
            set {
                this["CommunicationPeriodMilliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".exe")]
        public string ApplicationFileExtension {
            get {
                return ((string)(this["ApplicationFileExtension"]));
            }
            set {
                this["ApplicationFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SOFTWARE\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run")]
        public string UserStartupRegistryPath {
            get {
                return ((string)(this["UserStartupRegistryPath"]));
            }
            set {
                this["UserStartupRegistryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Реквизиты сетевых подкючений")]
        public string NetworkAdaptersRequisitesFromTitle {
            get {
                return ((string)(this["NetworkAdaptersRequisitesFromTitle"]));
            }
            set {
                this["NetworkAdaptersRequisitesFromTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PATH")]
        public string PathEnvironmentVariableName {
            get {
                return ((string)(this["PathEnvironmentVariableName"]));
            }
            set {
                this["PathEnvironmentVariableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("type=lan_diag&gwrs={0}&rk1rs={1}&ggrs={2}&gwlost={3}&rk1lost={4}&gglost={5}&biggw" +
            "rs={6}&bigrk1rs={7}&bigggrs={8}&biggwlost={9}&bigrk1lost={10}&biggglost={11}&lan" +
            "iperfip={12}&laniperfspeed={13}&osv={14}&d_ip={15}&d_mac={16}&d_t={17}")]
        public string PostDiagnosticsResultFormat {
            get {
                return ((string)(this["PostDiagnosticsResultFormat"]));
            }
            set {
                this["PostDiagnosticsResultFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Баланс")]
        public string ShowBalanceTitle {
            get {
                return ((string)(this["ShowBalanceTitle"]));
            }
            set {
                this["ShowBalanceTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("При выполнении проверки скорости произошла ошибка")]
        public string SpeedTestError {
            get {
                return ((string)(this["SpeedTestError"]));
            }
            set {
                this["SpeedTestError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("При выполнении проверки скорости произошёл сбой")]
        public string SpeedTestFail {
            get {
                return ((string)(this["SpeedTestFail"]));
            }
            set {
                this["SpeedTestFail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("type=balance")]
        public string BalanceRequest {
            get {
                return ((string)(this["BalanceRequest"]));
            }
            set {
                this["BalanceRequest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Построение маршрута завершенно")]
        public string TraceCompliteMessage {
            get {
                return ((string)(this["TraceCompliteMessage"]));
            }
            set {
                this["TraceCompliteMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("86400000")]
        public int DayInMilliseconds {
            get {
                return ((int)(this["DayInMilliseconds"]));
            }
            set {
                this["DayInMilliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Здесь будут написаны реквизиты сетевых соединений . Пожалуйста ждите")]
        public string NetworkRequisitesWillBeHere {
            get {
                return ((string)(this["NetworkRequisitesWillBeHere"]));
            }
            set {
                this["NetworkRequisitesWillBeHere"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("netsh.exe")]
        public string NetshExecutable {
            get {
                return ((string)(this["NetshExecutable"]));
            }
            set {
                this["NetshExecutable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("interface ipv4 show config")]
        public string NetshProgramArguments {
            get {
                return ((string)(this["NetshProgramArguments"]));
            }
            set {
                this["NetshProgramArguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Построение маршрута завершенно")]
        public string TraceComplite {
            get {
                return ((string)(this["TraceComplete"]));
            }
            set {
                this["TraceComplete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("866")]
        public int CmdCodePage {
            get {
                return ((int)(this["CmdCodePage"]));
            }
            set {
                this["CmdCodePage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("РусКом Контакты")]
        public string ShowContactsTitle {
            get {
                return ((string)(this["ShowContactsTitle"]));
            }
            set {
                this["ShowContactsTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Абон.отдел:
Адрес: Щорса, д. 7
Телефон: 251-93-00
e-mail: rk1@rk1.ru
Время работы:
С ПОНЕДЕЛЬНИКА ПО ПЯТНИЦУ 
С 09:00 ДО 20:00 
СУББОТА, ВОСКРЕСЕНЬЕ – ВЫХОДНОЙ


Тех.поддержка:
Телефон: 221-32-50
e-mail: support@rk1.ru
Время работы:
С 08:00 до 23:00
КАЖДЫЙ ДЕНЬ
")]
        public string ShowContactsMessage {
            get {
                return ((string)(this["ShowContactsMessage"]));
            }
            set {
                this["ShowContactsMessage"] = value;
            }
        }
    }
}
